server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ss?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    password: 290390
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  redis:
    port: 6379
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml